[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22.14.0"

# Handle SPA routing for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
